"""init_tables

Revision ID: 5c517c983973
Revises: 
Create Date: 2025-12-03 12:31:03.516008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlmodel.sql import sqltypes


# revision identifiers, used by Alembic.
revision: str = '5c517c983973'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt',
    sa.Column('id', sqltypes.AutoString(), nullable=False),
    sa.Column('purpose', sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqltypes.AutoString(), nullable=False),
    sa.Column('template', sqltypes.AutoString(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_name'), 'prompt', ['name'], unique=False)
    op.create_table('promptusage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt_id', sqltypes.AutoString(), nullable=False),
    sa.Column('document_text', sa.Text(), nullable=False),
    sa.Column('llm_response', sa.Text(), nullable=False),
    sa.Column('latency', sa.Integer(), nullable=False),
    sa.Column('model_used', sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompt.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promptusage_prompt_id'), 'promptusage', ['prompt_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_promptusage_prompt_id'), table_name='promptusage')
    op.drop_table('promptusage')
    op.drop_index(op.f('ix_prompt_name'), table_name='prompt')
    op.drop_table('prompt')
    # ### end Alembic commands ###
